services:
  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile.app-frontend
    container_name: app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app-frontend:/app
      - app_frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  # 1. THE BACKEND SERVER
  backend: 
    build: 
      context: ./app-backend
      dockerfile: Dockerfile.app-backend
    container_name: app-backend
    ports:
      - "8000:8000"
    environment:
      - LLM_URL=http://llm_service:11434
      - STT_URL=http://stt_service:5000
      - TTS_URL=http://tts_service:5001
    depends_on:
      llm_service:
        condition: service_started
      stt_service:
        condition: service_started
      tts_service:
        condition: service_started
    volumes:
      - ./app-backend/src:/app/src
    restart: unless-stopped

  # 2. THE LLM SERVER (Ollama)
  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile.llm 
    container_name: llm_service
    runtime: nvidia 
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    restart: unless-stopped

  # 3. STT SERVICE (Faster Whisper)
  stt_service:
    build: 
      context: ./stt_service
      dockerfile: Dockerfile.stt
    container_name: stt_service
    ports:
      - "5000:5000"
    runtime: nvidia
    shm_size: '2gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./stt_service/model_cache:/app/hf_cache
    environment:
      - WHISPER_MODEL=medium
    restart: unless-stopped

  # 4. TTS SERVICE (Piper)
  tts_service:
    build: 
      context: ./tts_service
      dockerfile: Dockerfile.tts
    container_name: tts_service
    ports:
      - "5001:5001"
    volumes:
      - ./tts_service:/app
    restart: unless-stopped

volumes:
  app_frontend_node_modules: